In [143]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score
from sklearn.metrics import roc_auc_score
import json
from tqdm import tqdm
from catboost import CatBoostClassifier

In [4]:
file_path = './data/data_correct.json'
with open(file_path, 'r') as file:
        data = json.load(file)

In [5]:
df = pd.DataFrame(data)

In [6]:
df['domain'].value_counts()

domain
human      34713
Llama2     17214
chatgpt     4154
Llama3      1966
GPT3.5      1882
Qwen        1868
Name: count, dtype: int64

In [7]:
data[11]

{'text': 'The paper effectively addresses an important problem in the field of entity recognition by proposing a new model based on multigraphs. This approach is novel and has the potential to overcome the limitations of existing models that utilize simple graphs. The experiments conducted on standard datasets provide evidence of the superior performance of the proposed model compared to previous models. The results indicate that the multigraph-based model is capable of accurately predicting overlapping entities, which is a challenging task. The analysis presented in the paper on the differences between the proposed model and previous models sheds light on the underlying mechanisms and highlights the strengths of the multigraph-based approach. This contributes to a better understanding of the problem and provides valuable insights for future research. The claim that this is the first structured prediction model utilizing multigraphs for predicting overlapping structures is significant, as it pushes the boundaries of existing methodologies and opens up new avenues for exploration. Overall, the paper is well-written and the findings are presented in a clear and coherent manner. However, it would be beneficial if the authors could further elaborate on the possible implications of the differences between the proposed model and previous models, as this could provide additional depth to the discussion section.',
 'label': 'machine_text',
 'domain': 'chatgpt'}

In [8]:
ppl_llama3 = np.load('./data/ppl_llama3.npy')
ppl_llama2 = np.load('./data/ppl_llama2.npy')
ppl_qwen = np.load('./data/ppl_qwen.npy')

In [9]:
ppl_llama3

array([27.469696, 13.407839, 22.490164, ..., 15.157976,  4.548979,
        9.542872], dtype=float32)

In [10]:
ppl_llama2

array([ 5812.8022,  3171.1804,  3527.042 , ..., 14197.993 ,  7160.3774,
        5744.6646], dtype=float32)

In [11]:
ppl_qwen

array([24.274326 , 13.989251 , 23.692776 , ..., 21.28179  ,  7.3349366,
        8.859068 ], dtype=float32)

In [15]:
data = pd.DataFrame(data)

In [16]:
data.groupby('label').domain.value_counts()

label         domain
human_text    human      34713
machine_text  Llama2     17214
              chatgpt     4154
              Llama3      1966
              GPT3.5      1882
              Qwen        1868
Name: count, dtype: int64

In [17]:
data['ppl_llama3'] = ppl_llama3
data['ppl_llama2'] = ppl_llama2
data['ppl_qwen'] = ppl_qwen

In [18]:
data

,text,label,domain,ppl_llama3,ppl_llama2,ppl_qwen
0,- Strengths:\n* Outperforms ALIGN in supervise...,human_text,human,27.469696,5812.802246,24.274326
1,the mention or also includes other related ent...,machine_text,chatgpt,13.407839,3171.180420,13.989251
2,This paper addresses the problem of disambigua...,human_text,human,22.490164,3527.041992,23.692776
3,For entities: their profiles consist of neighb...,machine_text,chatgpt,9.320074,3041.216553,12.446774
4,"- Strengths:\nGood ideas, simple neural learni...",human_text,human,33.169468,3590.321533,34.518867
...,...,...,...,...,...,...
61792,Bobby Douglas also suggested an American woman...,human_text,human,18.652077,4219.416504,19.506374
61793,"Ursula von der Leyen, a close ally of Chancell...",human_text,human,11.092178,6800.665039,12.950030
61794,The hosts' display was uncertain and their opp...,machine_text,Qwen,15.157976,14197.993164,21.281790
61795,Birkhoff-Smale theorem says that transverse ho...,machine_text,Llama3,4.548979,7160.377441,7.334937
61796,"Rothko's No 1 (Royal Red and Blue), described ...",human_text,human,9.542872,5744.664551,8.859068

In [21]:
data['target'] = data['domain'].apply(lambda x: 1 if x in ['Qwen', 'Llama2', 'Llama3'] else 0)

In [22]:
data

,text,label,domain,ppl_llama3,ppl_llama2,ppl_qwen,target
0,- Strengths:\n* Outperforms ALIGN in supervise...,human_text,human,27.469696,5812.802246,24.274326,0
1,the mention or also includes other related ent...,machine_text,chatgpt,13.407839,3171.180420,13.989251,0
2,This paper addresses the problem of disambigua...,human_text,human,22.490164,3527.041992,23.692776,0
3,For entities: their profiles consist of neighb...,machine_text,chatgpt,9.320074,3041.216553,12.446774,0
4,"- Strengths:\nGood ideas, simple neural learni...",human_text,human,33.169468,3590.321533,34.518867,0
...,...,...,...,...,...,...,...
61792,Bobby Douglas also suggested an American woman...,human_text,human,18.652077,4219.416504,19.506374,0
61793,"Ursula von der Leyen, a close ally of Chancell...",human_text,human,11.092178,6800.665039,12.950030,0
61794,The hosts' display was uncertain and their opp...,machine_text,Qwen,15.157976,14197.993164,21.281790,1
61795,Birkhoff-Smale theorem says that transverse ho...,machine_text,Llama3,4.548979,7160.377441,7.334937,1
61796,"Rothko's No 1 (Royal Red and Blue), described ...",human_text,human,9.542872,5744.664551,8.859068,0

In [24]:
data['is_llama2'] = (data['domain'].apply(lambda x: 'Llama2' == x))

In [23]:
data['is_llama3'] = (data['domain'].apply(lambda x: 'Llama3' == x))

In [25]:
data['is_qwen'] = (data['domain'].apply(lambda x: 'Qwen' == x))

In [26]:
data

,text,label,domain,ppl_llama3,ppl_llama2,ppl_qwen,target,is_llama3,is_llama2,is_qwen
0,- Strengths:\n* Outperforms ALIGN in supervise...,human_text,human,27.469696,5812.802246,24.274326,0,False,False,False
1,the mention or also includes other related ent...,machine_text,chatgpt,13.407839,3171.180420,13.989251,0,False,False,False
2,This paper addresses the problem of disambigua...,human_text,human,22.490164,3527.041992,23.692776,0,False,False,False
3,For entities: their profiles consist of neighb...,machine_text,chatgpt,9.320074,3041.216553,12.446774,0,False,False,False
4,"- Strengths:\nGood ideas, simple neural learni...",human_text,human,33.169468,3590.321533,34.518867,0,False,False,False
...,...,...,...,...,...,...,...,...,...,...
61792,Bobby Douglas also suggested an American woman...,human_text,human,18.652077,4219.416504,19.506374,0,False,False,False
61793,"Ursula von der Leyen, a close ally of Chancell...",human_text,human,11.092178,6800.665039,12.950030,0,False,False,False
61794,The hosts' display was uncertain and their opp...,machine_text,Qwen,15.157976,14197.993164,21.281790,1,False,False,True
61795,Birkhoff-Smale theorem says that transverse ho...,machine_text,Llama3,4.548979,7160.377441,7.334937,1,True,False,False
61796,"Rothko's No 1 (Royal Red and Blue), described ...",human_text,human,9.542872,5744.664551,8.859068,0,False,False,False

In [75]:
best_i_llama3 = 0
best_score_llama3 = 0
best_i_llama2 = 0
best_score_llama2 = 0
best_i_qwen = 0
best_score_qwen = 0

for i in tqdm(data.index):
    pred = data['ppl_llama3'] < data['ppl_llama3'][i]
    # score = f1_score(data['is_gpt'], pred)
    score = (data['is_llama3'] == pred).sum()
    if score > best_score_llama3:
        best_i_llama3 = data['ppl_llama3'][i]
        best_score_llama3 = score
    pred = data['ppl_llama2'] < data['ppl_llama2'][i]
    # score = f1_score(data['is_llama'], pred)
    score = (data['is_llama2'] == pred).sum()
    if score > best_score_llama2:
        best_i_llama2 = data['ppl_llama2'][i]
        best_score_llama2 = score
    pred = data['ppl_qwen'] < data['ppl_qwen'][i]
    # score = f1_score(data['is_qwen'], pred)
    score = (data['is_qwen'] == pred).sum()
    if score > best_score_qwen:
        best_i_qwen = data['ppl_qwen'][i]
        best_score_qwen = score

100%|██████████████████████████████████████████████████████████████████████████| 61700/61700 [00:43<00:00, 1420.25it/s]

In [179]:
print(f"Максимальное значение perplexity Llama 2 {max(ppl_llama2)},\nГраничное значение для Llama2 {best_i_llama2},\nЛучший скор для Llama2 {best_score_llama2}")

Максимальное значение perplexity Llama 2 54845.18359375,
Граничное значение для Llama2 1786.2454833984375,
Лучший скор для Llama2 44726

In [180]:
print(f"Максимальное значение perplexity Llama 3 {max(ppl_llama3)},\nГраничное значение для Llama3 {best_i_llama3},\nЛучший скор для Llama3 {best_score_llama3}")

Максимальное значение perplexity Llama 3 137674.734375,
Граничное значение для Llama3 1.1858340501785278,
Лучший скор для Llama3 59734

In [182]:
print(f"Максимальное значение perplexity Qwen {max(ppl_qwen)},\nГраничное значение для Qwen {best_i_qwen},\nЛучший скор для Qwen {best_score_qwen}")

Максимальное значение perplexity Qwen 202628.5,
Граничное значение для Qwen 1.1632660627365112,
Лучший скор для Qwen 59832

In [71]:
data[data['ppl_qwen'].apply(lambda x: math.isnan(x))]

Empty DataFrame
Columns: [text, label, domain, ppl_llama3, ppl_llama2, ppl_qwen, target, is_llama3, is_llama2, is_qwen]
Index: []

In [113]:
data[(data['ppl_llama3'] > best_i_llama3) & (data['ppl_llama2'] > best_i_llama2) & (data['ppl_qwen'] > best_i_qwen)]

,text,label,domain,ppl_llama3,ppl_llama2,ppl_qwen,target,is_llama3,is_llama2,is_qwen
0,- Strengths:\n* Outperforms ALIGN in supervise...,human_text,human,27.469696,5812.802246,24.274326,0,False,False,False
1,the mention or also includes other related ent...,machine_text,chatgpt,13.407839,3171.180420,13.989251,0,False,False,False
2,This paper addresses the problem of disambigua...,human_text,human,22.490164,3527.041992,23.692776,0,False,False,False
3,For entities: their profiles consist of neighb...,machine_text,chatgpt,9.320074,3041.216553,12.446774,0,False,False,False
4,"- Strengths:\nGood ideas, simple neural learni...",human_text,human,33.169468,3590.321533,34.518867,0,False,False,False
...,...,...,...,...,...,...,...,...,...,...
61792,Bobby Douglas also suggested an American woman...,human_text,human,18.652077,4219.416504,19.506374,0,False,False,False
61793,"Ursula von der Leyen, a close ally of Chancell...",human_text,human,11.092178,6800.665039,12.950030,0,False,False,False
61794,The hosts' display was uncertain and their opp...,machine_text,Qwen,15.157976,14197.993164,21.281790,1,False,False,True
61795,Birkhoff-Smale theorem says that transverse ho...,machine_text,Llama3,4.548979,7160.377441,7.334937,1,True,False,False
61796,"Rothko's No 1 (Royal Red and Blue), described ...",human_text,human,9.542872,5744.664551,8.859068,0,False,False,False

In [114]:
data.target.value_counts()

target
0    40749
1    20951
Name: count, dtype: int64

In [183]:
X = data[['ppl_llama3', 'ppl_llama2', 'ppl_qwen']]
y = data.target

In [184]:
X_train, X_test, y_train, y_test = train_test_split(data[['ppl_llama3', 'ppl_llama2', 'ppl_qwen']], data.target, test_size=0.25, stratify=data.target)

In [185]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler().set_output(transform='pandas')
mms.fit(X_train)

X_train = mms.transform(X_train)
X_test = mms.transform(X_test)

In [186]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [187]:
pred_train = lr.predict(X_train)
pred_test = lr.predict(X_test)

In [188]:
print(classification_report(y_train, pred_train))
print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.66      1.00      0.80     30562
           1       1.00      0.00      0.00     15713

    accuracy                           0.66     46275
   macro avg       0.83      0.50      0.40     46275
weighted avg       0.78      0.66      0.53     46275

              precision    recall  f1-score   support

           0       0.66      1.00      0.80     10187
           1       1.00      0.00      0.00      5238

    accuracy                           0.66     15425
   macro avg       0.83      0.50      0.40     15425
weighted avg       0.78      0.66      0.53     15425

In [189]:
pred_train = lr.predict_proba(X_train)
pred_test = lr.predict_proba(X_test)

In [191]:
from sklearn.metrics import roc_auc_score

print(f"ROC-AUC на трейне: {roc_auc_score(y_train, pred_train[:,1])}")
print(f"ROC-AUC на тесте: {roc_auc_score(y_test, pred_test[:,1])}")

ROC-AUC на трейне: 0.576690205232425
ROC-AUC на тесте: 0.5786115973412498

In [192]:
cb = CatBoostClassifier(verbose=False)

In [193]:
cb.fit(X_train, y_train)

In [194]:
pred_train = cb.predict(X_train)
pred_test = cb.predict(X_test)

In [195]:
print(classification_report(y_train, pred_train))
print(classification_report(y_test, pred_test))

              precision    recall  f1-score   support

           0       0.85      0.90      0.87     30562
           1       0.78      0.68      0.73     15713

    accuracy                           0.83     46275
   macro avg       0.81      0.79      0.80     46275
weighted avg       0.82      0.83      0.82     46275

              precision    recall  f1-score   support

           0       0.83      0.89      0.86     10187
           1       0.75      0.65      0.70      5238

    accuracy                           0.81     15425
   macro avg       0.79      0.77      0.78     15425
weighted avg       0.81      0.81      0.81     15425

In [196]:
pred_train = cb.predict_proba(X_train)
pred_test = cb.predict_proba(X_test)

In [198]:
print(f"ROC-AUC на трейне: {roc_auc_score(y_train, pred_train[:,1])}")
print(f"ROC-AUC на тесте: {roc_auc_score(y_test, pred_test[:,1])}")

ROC-AUC на трейне: 0.8839402074845144
ROC-AUC на тесте: 0.8583649743683909

In [199]:
import optuna
from sklearn.model_selection import cross_val_score
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 100, 1000),
        'depth': trial.suggest_int('depth', 4, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1, 10),
        'random_strength': trial.suggest_float('random_strength', 0.1, 10),
        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.0, 1.0),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 20),
        'verbose': False,
        'early_stopping_rounds': 50,
    }
    
    # Используем кросс-валидацию
    model = CatBoostClassifier(**params)
    scores = cross_val_score(model, X_train, y_train, cv=3, scoring='roc_auc')
    return np.mean(scores)
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

print("Лучшие параметры:", study.best_params)
print("Лучшее значение AUC-ROC:", study.best_value)

[I 2025-05-14 22:59:44,040] A new study created in memory with name: no-name-775822bc-e1e1-4351-8ed2-df367498992c
[I 2025-05-14 22:59:52,842] Trial 0 finished with value: 0.8357894713300169 and parameters: {'iterations': 217, 'depth': 8, 'learning_rate': 0.04124775538983445, 'l2_leaf_reg': 1.3678203065649002, 'random_strength': 7.879382672028832, 'bagging_temperature': 0.25144400561527225, 'min_data_in_leaf': 3}. Best is trial 0 with value: 0.8357894713300169.
[I 2025-05-14 23:00:19,896] Trial 1 finished with value: 0.8666827625316417 and parameters: {'iterations': 644, 'depth': 8, 'learning_rate': 0.18524186971325907, 'l2_leaf_reg': 7.5555533434353315, 'random_strength': 6.891354866698466, 'bagging_temperature': 0.4960155949684345, 'min_data_in_leaf': 13}. Best is trial 1 with value: 0.8666827625316417.
[I 2025-05-14 23:00:52,223] Trial 2 finished with value: 0.8673631052914278 and parameters: {'iterations': 423, 'depth': 9, 'learning_rate': 0.19370022565713638, 'l2_leaf_reg': 5.688269096973326, 'random_strength': 3.8662644691012233, 'bagging_temperature': 0.18010021411608224, 'min_data_in_leaf': 19}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:01:31,244] Trial 3 finished with value: 0.844827015099333 and parameters: {'iterations': 865, 'depth': 8, 'learning_rate': 0.01813701428369588, 'l2_leaf_reg': 9.46497013573236, 'random_strength': 6.001983623904745, 'bagging_temperature': 0.039337144331547336, 'min_data_in_leaf': 20}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:01:40,592] Trial 4 finished with value: 0.8458940333549911 and parameters: {'iterations': 123, 'depth': 10, 'learning_rate': 0.15314036217221316, 'l2_leaf_reg': 4.988000908977264, 'random_strength': 3.834596569622676, 'bagging_temperature': 0.7137988177252481, 'min_data_in_leaf': 20}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:02:19,173] Trial 5 finished with value: 0.8512635510501497 and parameters: {'iterations': 319, 'depth': 10, 'learning_rate': 0.06283607163445402, 'l2_leaf_reg': 5.6950746706738204, 'random_strength': 6.903470129021572, 'bagging_temperature': 0.0005798421156819611, 'min_data_in_leaf': 2}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:02:37,464] Trial 6 finished with value: 0.8633788011637388 and parameters: {'iterations': 478, 'depth': 8, 'learning_rate': 0.16574906569519623, 'l2_leaf_reg': 8.685890464686352, 'random_strength': 2.8279136666246094, 'bagging_temperature': 0.16613674765469366, 'min_data_in_leaf': 13}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:02:54,387] Trial 7 finished with value: 0.8625898106752254 and parameters: {'iterations': 379, 'depth': 8, 'learning_rate': 0.19788524050933343, 'l2_leaf_reg': 7.5049460455397945, 'random_strength': 5.733478059611852, 'bagging_temperature': 0.22353355602784386, 'min_data_in_leaf': 3}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:03:28,376] Trial 8 finished with value: 0.8629688663208676 and parameters: {'iterations': 451, 'depth': 9, 'learning_rate': 0.10582128408017374, 'l2_leaf_reg': 2.948049394682573, 'random_strength': 8.43025251031695, 'bagging_temperature': 0.659059845158421, 'min_data_in_leaf': 17}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:03:29,474] Trial 9 finished with value: 0.8327235753898764 and parameters: {'iterations': 107, 'depth': 4, 'learning_rate': 0.10382898082848918, 'l2_leaf_reg': 2.4886061448000576, 'random_strength': 1.4888319820422056, 'bagging_temperature': 0.12863613882695946, 'min_data_in_leaf': 7}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:03:43,439] Trial 10 finished with value: 0.8401272858584182 and parameters: {'iterations': 714, 'depth': 5, 'learning_rate': 0.016792872215821528, 'l2_leaf_reg': 4.8988874905558015, 'random_strength': 0.48725121179170383, 'bagging_temperature': 0.9218354650511443, 'min_data_in_leaf': 8}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:03:57,927] Trial 11 finished with value: 0.8626414179807713 and parameters: {'iterations': 655, 'depth': 6, 'learning_rate': 0.29915385531606353, 'l2_leaf_reg': 7.097158073008546, 'random_strength': 9.655105260812228, 'bagging_temperature': 0.38282037626790677, 'min_data_in_leaf': 13}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:04:14,785] Trial 12 finished with value: 0.8670878165639943 and parameters: {'iterations': 654, 'depth': 7, 'learning_rate': 0.2889890462076302, 'l2_leaf_reg': 6.627298225150247, 'random_strength': 4.1915702549591085, 'bagging_temperature': 0.47619126855177935, 'min_data_in_leaf': 16}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:04:34,023] Trial 13 finished with value: 0.8647247440543259 and parameters: {'iterations': 843, 'depth': 6, 'learning_rate': 0.2811877829264265, 'l2_leaf_reg': 5.984782922052348, 'random_strength': 3.927688111518865, 'bagging_temperature': 0.38440750925085554, 'min_data_in_leaf': 17}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:04:49,893] Trial 14 finished with value: 0.8522194502970852 and parameters: {'iterations': 555, 'depth': 7, 'learning_rate': 0.05469885964758839, 'l2_leaf_reg': 6.479723585007315, 'random_strength': 4.368376220355948, 'bagging_temperature': 0.6634724707556539, 'min_data_in_leaf': 18}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:05:10,902] Trial 15 finished with value: 0.859625726028835 and parameters: {'iterations': 774, 'depth': 6, 'learning_rate': 0.1014316711820762, 'l2_leaf_reg': 4.212552646660085, 'random_strength': 2.5494834393406407, 'bagging_temperature': 0.350178447216172, 'min_data_in_leaf': 15}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:05:52,079] Trial 16 finished with value: 0.8372023979061652 and parameters: {'iterations': 571, 'depth': 9, 'learning_rate': 0.010446913951282345, 'l2_leaf_reg': 3.695039310154059, 'random_strength': 2.8412953512326347, 'bagging_temperature': 0.5439279826374325, 'min_data_in_leaf': 10}. Best is trial 2 with value: 0.8673631052914278.
[I 2025-05-14 23:06:16,560] Trial 17 finished with value: 0.8694215802736944 and parameters: {'iterations': 971, 'depth': 7, 'learning_rate': 0.23652795473598187, 'l2_leaf_reg': 8.629151189481725, 'random_strength': 4.625059553540611, 'bagging_temperature': 0.8794148233716766, 'min_data_in_leaf': 15}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:07:26,696] Trial 18 finished with value: 0.858073831344122 and parameters: {'iterations': 959, 'depth': 9, 'learning_rate': 0.03686020744964768, 'l2_leaf_reg': 8.440242233526721, 'random_strength': 5.061486680988079, 'bagging_temperature': 0.9827978140014615, 'min_data_in_leaf': 14}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:07:45,711] Trial 19 finished with value: 0.8545809273357877 and parameters: {'iterations': 979, 'depth': 5, 'learning_rate': 0.07348476998409381, 'l2_leaf_reg': 9.700166660685955, 'random_strength': 1.135766770142062, 'bagging_temperature': 0.8183068743264696, 'min_data_in_leaf': 19}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:07:56,740] Trial 20 finished with value: 0.857050594522334 and parameters: {'iterations': 392, 'depth': 7, 'learning_rate': 0.14215892182556897, 'l2_leaf_reg': 8.620218259012873, 'random_strength': 2.1891391360532113, 'bagging_temperature': 0.814582491296154, 'min_data_in_leaf': 12}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:08:05,873] Trial 21 finished with value: 0.858689293727847 and parameters: {'iterations': 283, 'depth': 7, 'learning_rate': 0.23304146393703373, 'l2_leaf_reg': 6.489241263409818, 'random_strength': 4.7368190359716795, 'bagging_temperature': 0.5133342334102445, 'min_data_in_leaf': 16}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:08:31,505] Trial 22 finished with value: 0.8682629642689846 and parameters: {'iterations': 847, 'depth': 7, 'learning_rate': 0.24720956036957528, 'l2_leaf_reg': 7.994715357530559, 'random_strength': 3.549877224645991, 'bagging_temperature': 0.27966861008736954, 'min_data_in_leaf': 16}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:08:54,382] Trial 23 finished with value: 0.8614486396835105 and parameters: {'iterations': 859, 'depth': 6, 'learning_rate': 0.12754350515990776, 'l2_leaf_reg': 7.836491045987618, 'random_strength': 3.30111264116044, 'bagging_temperature': 0.3077856525147823, 'min_data_in_leaf': 18}. Best is trial 17 with value: 0.8694215802736944.
[I 2025-05-14 23:10:02,077] Trial 24 finished with value: 0.8736171413859793 and parameters: {'iterations': 900, 'depth': 9, 'learning_rate': 0.20933025644542286, 'l2_leaf_reg': 9.215875977649482, 'random_strength': 5.253650537747549, 'bagging_temperature': 0.10363837571604614, 'min_data_in_leaf': 11}. Best is trial 24 with value: 0.8736171413859793.
[I 2025-05-14 23:10:20,271] Trial 25 finished with value: 0.861377780977608 and parameters: {'iterations': 932, 'depth': 5, 'learning_rate': 0.23462050547909644, 'l2_leaf_reg': 9.114113560346302, 'random_strength': 5.545974675147305, 'bagging_temperature': 0.11489085973724311, 'min_data_in_leaf': 10}. Best is trial 24 with value: 0.8736171413859793.
[I 2025-05-14 23:10:40,382] Trial 26 finished with value: 0.8584627759890345 and parameters: {'iterations': 783, 'depth': 7, 'learning_rate': 0.07751156493527957, 'l2_leaf_reg': 9.87232452031642, 'random_strength': 6.620052639272457, 'bagging_temperature': 0.28816333217381773, 'min_data_in_leaf': 12}. Best is trial 24 with value: 0.8736171413859793.
[I 2025-05-14 23:12:27,378] Trial 27 finished with value: 0.8766407430160114 and parameters: {'iterations': 891, 'depth': 10, 'learning_rate': 0.22384812363041748, 'l2_leaf_reg': 8.063368947853444, 'random_strength': 5.130485513309777, 'bagging_temperature': 0.077015563987563, 'min_data_in_leaf': 6}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:14:17,122] Trial 28 finished with value: 0.8723434020127269 and parameters: {'iterations': 905, 'depth': 10, 'learning_rate': 0.12382252715907777, 'l2_leaf_reg': 9.15450640133593, 'random_strength': 5.364642458261486, 'bagging_temperature': 0.0843862231448016, 'min_data_in_leaf': 6}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:16:08,311] Trial 29 finished with value: 0.8725265636467695 and parameters: {'iterations': 914, 'depth': 10, 'learning_rate': 0.12278889977853119, 'l2_leaf_reg': 9.375543680011296, 'random_strength': 7.803704287400619, 'bagging_temperature': 0.06987262692778173, 'min_data_in_leaf': 5}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:17:42,754] Trial 30 finished with value: 0.8633650441074066 and parameters: {'iterations': 777, 'depth': 10, 'learning_rate': 0.04448451717201312, 'l2_leaf_reg': 1.2477267022811205, 'random_strength': 8.124140457064959, 'bagging_temperature': 0.05177280032269267, 'min_data_in_leaf': 5}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:19:33,064] Trial 31 finished with value: 0.872319683317904 and parameters: {'iterations': 907, 'depth': 10, 'learning_rate': 0.12977453243609935, 'l2_leaf_reg': 9.348851550899608, 'random_strength': 8.950457865922196, 'bagging_temperature': 0.09308148363962264, 'min_data_in_leaf': 5}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:21:23,122] Trial 32 finished with value: 0.8697300034282535 and parameters: {'iterations': 905, 'depth': 10, 'learning_rate': 0.09070017606368444, 'l2_leaf_reg': 8.966805805543679, 'random_strength': 6.998034882484429, 'bagging_temperature': 0.18460049716782023, 'min_data_in_leaf': 8}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:22:15,776] Trial 33 finished with value: 0.8697809398269586 and parameters: {'iterations': 731, 'depth': 9, 'learning_rate': 0.18273446000707544, 'l2_leaf_reg': 9.941146254256706, 'random_strength': 7.66241224688736, 'bagging_temperature': 0.0020213930482987225, 'min_data_in_leaf': 5}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:24:16,075] Trial 34 finished with value: 0.8750853802058537 and parameters: {'iterations': 1000, 'depth': 10, 'learning_rate': 0.12759390837424078, 'l2_leaf_reg': 7.294565941934252, 'random_strength': 6.382011684388324, 'bagging_temperature': 0.08781857629276232, 'min_data_in_leaf': 7}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:25:32,263] Trial 35 finished with value: 0.8748001705771159 and parameters: {'iterations': 998, 'depth': 9, 'learning_rate': 0.19441361118564193, 'l2_leaf_reg': 7.232173536773239, 'random_strength': 6.271007734977329, 'bagging_temperature': 0.22660558980894896, 'min_data_in_leaf': 3}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:26:45,010] Trial 36 finished with value: 0.8744064209059514 and parameters: {'iterations': 978, 'depth': 9, 'learning_rate': 0.19638172964761524, 'l2_leaf_reg': 7.4317785469284114, 'random_strength': 6.406097376963029, 'bagging_temperature': 0.21434319764844656, 'min_data_in_leaf': 1}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:27:59,994] Trial 37 finished with value: 0.8739501766476763 and parameters: {'iterations': 996, 'depth': 9, 'learning_rate': 0.16398002216334048, 'l2_leaf_reg': 7.1314583621397825, 'random_strength': 6.253319216053043, 'bagging_temperature': 0.22839222794360797, 'min_data_in_leaf': 1}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:28:37,090] Trial 38 finished with value: 0.8696149023710706 and parameters: {'iterations': 815, 'depth': 8, 'learning_rate': 0.18525603787232714, 'l2_leaf_reg': 7.197251856597443, 'random_strength': 7.310188383575395, 'bagging_temperature': 0.19801683371350132, 'min_data_in_leaf': 3}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:30:38,813] Trial 39 finished with value: 0.8576937918110641 and parameters: {'iterations': 996, 'depth': 10, 'learning_rate': 0.02971618969544, 'l2_leaf_reg': 8.042531240653059, 'random_strength': 6.224028427798595, 'bagging_temperature': 0.14341445181414256, 'min_data_in_leaf': 1}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:30:43,954] Trial 40 finished with value: 0.846790112128934 and parameters: {'iterations': 172, 'depth': 8, 'learning_rate': 0.1588645029969436, 'l2_leaf_reg': 5.104646695815771, 'random_strength': 6.584500824773156, 'bagging_temperature': 0.2360508030110577, 'min_data_in_leaf': 2}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:31:59,476] Trial 41 finished with value: 0.8736271142777241 and parameters: {'iterations': 999, 'depth': 9, 'learning_rate': 0.16256905259240467, 'l2_leaf_reg': 7.024187687691991, 'random_strength': 5.950159073568444, 'bagging_temperature': 0.22210464781220005, 'min_data_in_leaf': 1}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:33:10,874] Trial 42 finished with value: 0.8743436066859204 and parameters: {'iterations': 955, 'depth': 9, 'learning_rate': 0.20830142579880864, 'l2_leaf_reg': 7.512056088576111, 'random_strength': 6.237040403741892, 'bagging_temperature': 0.1618326966671758, 'min_data_in_leaf': 4}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:34:22,491] Trial 43 finished with value: 0.8739849032890336 and parameters: {'iterations': 952, 'depth': 9, 'learning_rate': 0.2036934761066688, 'l2_leaf_reg': 7.615777486463174, 'random_strength': 7.298095961043369, 'bagging_temperature': 0.16680547501148196, 'min_data_in_leaf': 3}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:36:07,727] Trial 44 finished with value: 0.8763637938358398 and parameters: {'iterations': 878, 'depth': 10, 'learning_rate': 0.2658607974574527, 'l2_leaf_reg': 6.067766408410576, 'random_strength': 6.4467581737847715, 'bagging_temperature': 0.019423846807852863, 'min_data_in_leaf': 4}. Best is trial 27 with value: 0.8766407430160114.
[I 2025-05-14 23:37:53,257] Trial 45 finished with value: 0.8773183526936285 and parameters: {'iterations': 874, 'depth': 10, 'learning_rate': 0.2755637621456317, 'l2_leaf_reg': 5.979424539976808, 'random_strength': 8.517876159086057, 'bagging_temperature': 0.0043982154993864216, 'min_data_in_leaf': 7}. Best is trial 45 with value: 0.8773183526936285.
[I 2025-05-14 23:39:32,703] Trial 46 finished with value: 0.877340754839922 and parameters: {'iterations': 817, 'depth': 10, 'learning_rate': 0.2677276657238807, 'l2_leaf_reg': 6.122800933328357, 'random_strength': 8.728944195423962, 'bagging_temperature': 0.015598614008097866, 'min_data_in_leaf': 7}. Best is trial 46 with value: 0.877340754839922.
[I 2025-05-14 23:41:01,514] Trial 47 finished with value: 0.8760622327040561 and parameters: {'iterations': 731, 'depth': 10, 'learning_rate': 0.2733806548978997, 'l2_leaf_reg': 5.975434716860849, 'random_strength': 9.651223656139054, 'bagging_temperature': 0.016052806216484212, 'min_data_in_leaf': 8}. Best is trial 46 with value: 0.877340754839922.
[I 2025-05-14 23:42:23,442] Trial 48 finished with value: 0.8753681051921322 and parameters: {'iterations': 691, 'depth': 10, 'learning_rate': 0.2703858880603482, 'l2_leaf_reg': 5.902988047359114, 'random_strength': 9.753214618438793, 'bagging_temperature': 0.0075347771006846285, 'min_data_in_leaf': 9}. Best is trial 46 with value: 0.877340754839922.
[I 2025-05-14 23:43:37,172] Trial 49 finished with value: 0.8746547137406671 and parameters: {'iterations': 607, 'depth': 10, 'learning_rate': 0.2900488586267616, 'l2_leaf_reg': 5.4758983454906485, 'random_strength': 8.871105924253763, 'bagging_temperature': 0.03301152217582352, 'min_data_in_leaf': 7}. Best is trial 46 with value: 0.877340754839922.

Лучшие параметры: {'iterations': 817, 'depth': 10, 'learning_rate': 0.2677276657238807, 'l2_leaf_reg': 6.122800933328357, 'random_strength': 8.728944195423962, 'bagging_temperature': 0.015598614008097866, 'min_data_in_leaf': 7}
Лучшее значение AUC-ROC: 0.877340754839922

In [ ]:
best_model = CatBoostClassifier(
    **study.best_params, verbose=100
)

best_model.fit(X_train, y_train)

0:	learn: 0.5986220	total: 56.6ms	remaining: 46.2s
100:	learn: 0.4047965	total: 3.97s	remaining: 28.2s
200:	learn: 0.3574028	total: 8.07s	remaining: 24.7s
300:	learn: 0.3242399	total: 12.2s	remaining: 20.9s
400:	learn: 0.2991669	total: 16.4s	remaining: 17s
500:	learn: 0.2756278	total: 20.6s	remaining: 13s
600:	learn: 0.2560708	total: 24.8s	remaining: 8.9s
700:	learn: 0.2384275	total: 29s	remaining: 4.8s

In [ ]:
pred_train = best_model.predict(X_train)
pred_test = best_model.predict(X_test)

In [ ]:
print(classification_report(y_train, pred_train))
print(classification_report(y_test, pred_test))

In [ ]:
pred_train = best_model.predict_proba(X_train)
pred_test = best_model.predict_proba(X_test)

In [ ]:
print(f"ROC-AUC на трейне: {roc_auc_score(y_train, pred_train[:,1])}")
print(f"ROC-AUC на тесте: {roc_auc_score(y_test, pred_test[:,1])}")